### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by geerlingguy** [jakecoffman/stldevs#12]
Because I'm so vain, I decided to hop over to http://www.stldevs.com/#!/topdevs today, and Chrome complained that `ERR_NAME_NOT_RESOLVED`.

Dig gives:

```
$ dig www.stldevs.com

; <<>> DiG 9.8.3-P1 <<>> www.stldevs.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3163
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;www.stldevs.com.		IN	A

;; AUTHORITY SECTION:
stldevs.com.		1696	IN	SOA	dns1.registrar-servers.com. hostmaster.registrar-servers.com. 2016082501 43200 3600 604800 3601

;; Query time: 3024 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Aug 25 17:07:32 2016
;; MSG SIZE  rcvd: 103
```

**Comment by jakecoffman** [comment]
If you drop the www it should work.

I messed with the subdomain today when I was trying to figure out TLS issues. I'll setup a forward so it doesn't break everyone's bookmarks.

**Comment by geerlingguy** [comment]
Well, there you have it! Chrome was forcing the www.; cleared cache and explicitly entered https://stldevs.com/#!/topdevs and it loads.
