### ISSUE TITLE
Who am I?

### ISSUE THREAD

**Issue by cuddyz** [jakecoffman/stldevs#14]
![screen shot 2018-10-23 at 10 26 59 am](https://user-images.githubusercontent.com/12533913/47371880-35cbc380-d6ae-11e8-927f-67d1fc8f4590.png)

💔 😢 😭

**Comment by jakecoffman** [comment]
once I get time to finish auth (#13) you'll be able to add yourself

**Comment by jakecoffman** [comment]
fixed by #15

https://stldevs.com/developers/cuddyz
