### ISSUE TITLE
Lots of errors on the site

### ISSUE THREAD

**Issue by sgnn7** [jakecoffman/stldevs#17]
I've noticed a huge number of issues in my last visit. I'm guessing the API limit is being reached when the dev page is opened due to concurrent requests for images/data.

<img width="1406" alt="Screen Shot 2020-09-15 at 13 22 54" src="https://user-images.githubusercontent.com/175811/93249321-bc806280-f756-11ea-87b9-1c3e3160270c.png">
<img width="483" alt="Screen Shot 2020-09-15 at 13 23 14" src="https://user-images.githubusercontent.com/175811/93249330-bee2bc80-f756-11ea-8e22-a4714dcea8a2.png">
<img width="1005" alt="Screen Shot 2020-09-15 at 13 23 21" src="https://user-images.githubusercontent.com/175811/93249332-bee2bc80-f756-11ea-896d-4cfc3fd10ffd.png">

**Comment by geerlingguy** [comment]
Just visiting the site and refreshing a few times, I didn't notice these errors. Maybe there was a temporary rate limit being hit?

**Comment by sgnn7** [comment]
Maybe but I just tried the same thing on Chrome (the original issue was on FF) and I see the same issues. You should be able to see the 500s in the server logs since those are internal server errors. I think you can also try incognito to make sure it's not cached data on your machine.

**Comment by jakecoffman** [comment]
I think the service worker is broken (again). Incognito shows the errors like in your screenshots but then a hard refresh fixes it. 🤷 

I gotta do some work right now but I can get this fixed today. Thanks for the report @sgnn7!

(If you want to look sooner the UI is over here https://github.com/jakecoffman/stldevs-sapper)

**Comment by jakecoffman** [comment]
I think it's fixed now.

It turns out that incognito mode has a really small cache that service-workers can use. The cache was filling up, so the `put` call was throwing.

Also turns out that in some browsers you don't see the console.logs from the service-worker in the console. 🤣
