### ISSUE TITLE
Pagination counts incorrect

### ISSUE THREAD

**Issue by mikemcbride** [jakecoffman/stldevs#18]
It looks like the counts returned from the API, which drive the page numbers, might be incorrect. I can manually update the page query and get results beyond what I expect:

https://stldevs.com/languages/Go?p=9

If I go way beyond, it eventually says there are no more results:

https://stldevs.com/languages/Go?p=30

Happy to help troubleshoot but I'm not too familiar with Go

**Comment by jakecoffman** [comment]
fixed by 045b2dca67722167d33bd5b2cf0dae55489cde4e
