### ISSUE TITLE
Show organizations as well as users

### ISSUE THREAD

**Issue by booch** [jakecoffman/stldevs#9]
It's not 100% clear to me whether organizations are supported or not. [lambdalounge](http://www.stldevs.com/#!/profile/lambdalounge) is an organization that's showing up. But my organization, [boochtek](https://github.com/boochtek/) is not. It's got "St. Louis" listed in the location. Not sure if it didn't get picked up because it's an organization, and Lambda Lounge was added manually, or if there's some other issue.

**Comment by jakecoffman** [comment]
I checked the search, it should be picking up `boochtek` in the scan but it's not. I reran it last night, must be a bug. I should have more time to look at it soon. I haven't touched the project in so long it still has references to code.google.com so I need to do some cleanup.

**Comment by jakecoffman** [comment]
I rolled out an initial implementation of organizations just now.

https://www.stldevs.com/#!/toporgs

Not sure if Github changed their API and lambda lounge got caught up as a user or what but things should make more sense now.

**Comment by booch** [comment]
Thanks! Looks great.
